### ISSUE TITLE
Navigation issue via Client

### ISSUE THREAD

**Issue by cunning-folk** [cunning-folk/Wholeview_Medicaid#9]
On desktop, the top hamburger menu on the upper right corner of the screen, when you click it, you get an “X”, but you can’t click on any of the other options 

![Image](https://user-images.githubusercontent.com/31627480/193633782-a84a7511-103d-4697-9040-123383efe518.png)
![Image](https://user-images.githubusercontent.com/31627480/193633781-bc85d56e-0d7c-4098-aa9c-8358494921e1.png)

**Comment by jeremylenz** [comment]
Turns out this was an issue with the breakpoints - after https://github.com/CunningFolkDev/elevate360_website/issues/226 there were still a few more that needed to be changed to 1320px from 768px.

**Comment by cunning-folk** [comment]
Here is the big where the nav disappears: https://www.icloud.com/iclouddrive/057zHEo1ZY6JYSIC7FpmB-zJw#Navigation_Bug

I am still getting this bug locally. The navigation items disappear when I roll over the nav panel.

Also getting a bug with the way the menu renders Tablet width.

![Image](https://user-images.githubusercontent.com/31627480/193875519-7744982e-8373-4609-beed-fd9511f8d9e6.png)

@lukemiller

I checked the two staging links I have both in Siteleaf and http://www.wholeview.co.s3-website-us-east-1.amazonaws.com/

Same issue

**Comment by jeremylenz** [comment]
@cunning-folk Check the preview now; I think the crowded text issue should be better now.

The nav closing prematurely is super weird. I opened another issue for it: https://github.com/CunningFolkDev/elevate360_website/issues/228

It looks like what's happening is that there's a [`mouseleave` event](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseleave_event) on the `<nav>` which is triggering the menu close. This would normally be by design, except it seems to be triggered whenever I move my mouse cursor to any of the `<a>` tags for the main nav titles ('About Us', 'Services', etc.)

I have no idea why this is happening or why it just started now. I'll keep trying to figure it out but if y'all have any hints please let me know :)

**Comment by jeremylenz** [comment]
Closing as duplicate of https://github.com/CunningFolkDev/elevate360_website/issues/228
